suro: required
services:
    - docker

before_install: 
    - docker build -t porzechowski/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true porzechowski/react-test npm test

after_success:
    - docker build -t porzechowski/multi-client ./client
    - docker build -t porzechowski/multi-nginx ./nginx
    - docker build -t porzechowski/multi-server ./server
    - docker build -t porzechowski/multi-worker ./worker

    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        
    # Take images and push them to docker hub
    - docker push porzechowski/multi-client
    - docker push porzechowski/multi-nginx
    - docker push porzechowski/multi-server
    - docker push porzechowski/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-317792549218
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY